# AI Navigation Index for Structurify SDK
# This file is the authoritative source of truth for SDK code navigation
# Last updated: 2026-01-02
# Copyright (c) 2026 REDSCVRY TECHNOLOGY PRIVATE LIMITED

version: 1.0

project_overview:
  name: Structurify SDK
  description: |
    Official SDKs (Python, Node.js) and REST API documentation for programmatic
    access to the Structurify document extraction platform.

  base_url: https://app.structurify.ai/api

  authentication:
    method: API Keys only (no JWT in SDK)
    format: sk_live_<32_random_chars>
    header: "Authorization: Bearer <api_key>" or "X-API-Key: <api_key>"
    generation: Admin-only (users request, platform admin approves)

  monetization:
    model: Existing credits system
    cost: 1 credit = 1 document extraction
    consistency: Same as web UI

  rate_limits:
    default_per_minute: 60
    default_per_day: 10000
    headers:
      - X-RateLimit-Limit
      - X-RateLimit-Remaining
      - X-RateLimit-Reset

domains:
  # =============================================================================
  # OPENAPI SPECIFICATION
  # =============================================================================
  openapi:
    description: REST API specification in OpenAPI 3.0 format
    files:
      - path: openapi/structurify-api.yaml
        responsibility: Complete API specification with schemas and endpoints
        endpoints:
          - GET /project-templates - List project templates
          - GET /templates - List column templates
          - POST /projects - Create project (requires templateId)
          - GET /projects - List projects
          - GET /projects/{id} - Get project details
          - DELETE /projects/{id} - Delete project
          - POST /documents - Upload document
          - GET /documents/{id} - Get document metadata
          - GET /documents/{id}/content - Get document content (base64)
          - DELETE /documents/{id} - Delete document
          - POST /extraction-jobs - Run extraction
          - GET /extraction-jobs/{id} - Get job status
          - DELETE /extraction-jobs/{id} - Cancel job
          - POST /exports - Create export
          - GET /exports/{id}/download - Download export

    important_notes: |
      - Projects MUST be created from templates (templateId required)
      - No custom column creation via SDK - template-based only
      - Extraction consumes 1 credit per document
      - Large exports return downloadUrl, small exports include inline data

  # =============================================================================
  # PYTHON SDK
  # =============================================================================
  python_sdk:
    description: Official Python SDK for Structurify API
    package_name: structurify
    python_versions: ">=3.8"

    files:
      - path: python/pyproject.toml
        responsibility: Package configuration, dependencies, metadata

      - path: python/structurify/__init__.py
        responsibility: Package exports and version
        exports:
          - Structurify
          - StructurifyError
          - AuthenticationError
          - RateLimitError
          - NotFoundError
          - ValidationError
          - InsufficientCreditsError

      - path: python/structurify/client.py
        responsibility: Main client class with HTTP methods
        features:
          - Automatic retry with exponential backoff
          - Rate limit handling
          - Error mapping to typed exceptions
        methods:
          - get(path, params)
          - post(path, json, data, files)
          - put(path, json)
          - delete(path)

      - path: python/structurify/exceptions.py
        responsibility: Custom exception classes
        classes:
          - StructurifyError (base)
          - AuthenticationError (401)
          - RateLimitError (429)
          - NotFoundError (404)
          - ValidationError (400)
          - InsufficientCreditsError (402)
          - ServerError (500)

      - path: python/structurify/webhooks.py
        responsibility: Webhook signature verification
        functions:
          - verify_signature(payload, signature, secret) -> bool
          - compute_signature(payload, secret) -> str

      - path: python/structurify/resources/templates.py
        responsibility: Templates resource handler
        methods:
          - list() - List project templates
          - list_columns() - List column templates
          - get(template_id) - Get specific template

      - path: python/structurify/resources/projects.py
        responsibility: Projects resource handler
        methods:
          - list() - List all projects
          - get(project_id) - Get project with columns/documents
          - create(name, template_id, description?) - Create from template
          - update(project_id, name) - Update project name
          - delete(project_id) - Delete project

      - path: python/structurify/resources/documents.py
        responsibility: Documents resource handler
        methods:
          - upload(project_id, file_path?, file_bytes?, file_obj?, name?, mime_type?)
          - upload_multipart(project_id, file_path, name?) - For large files
          - get(document_id) - Get metadata
          - get_content(document_id) - Get base64 content
          - download(document_id) - Get raw bytes
          - delete(document_id)

      - path: python/structurify/resources/extraction.py
        responsibility: Extraction jobs resource handler
        methods:
          - run(project_id) - Start extraction job
          - get(job_id) - Get job status
          - cancel(job_id) - Cancel job
          - wait_for_completion(job_id, timeout=300, poll_interval=2.0)
          - list(project_id) - List jobs for project

      - path: python/structurify/resources/exports.py
        responsibility: Exports resource handler
        methods:
          - create(project_id, format, document_ids?)
          - get(export_id)
          - download(export_id)
          - list(project_id)
          - delete(export_id)

    usage_example: |
      from structurify import Structurify

      client = Structurify(api_key="sk_live_xxx")

      # List templates
      templates = client.templates.list()

      # Create project from template
      project = client.projects.create(
          name="Q1 Invoices",
          template_id="tpl_invoice"
      )

      # Upload document
      doc = client.documents.upload(
          project_id=project["id"],
          file_path="invoice.pdf"
      )

      # Run extraction
      job = client.extraction.run(project_id=project["id"])
      completed = client.extraction.wait_for_completion(job["id"])

      # Export results
      export = client.exports.create(project_id=project["id"], format="csv")

  # =============================================================================
  # NODE.JS SDK
  # =============================================================================
  nodejs_sdk:
    description: Official Node.js SDK for Structurify API
    package_name: "@structurify/sdk"
    node_version: ">=18.0.0"

    files:
      - path: nodejs/package.json
        responsibility: Package configuration, dependencies, scripts

      - path: nodejs/tsconfig.json
        responsibility: TypeScript compiler configuration

      - path: nodejs/tsup.config.ts
        responsibility: Build configuration (CJS + ESM output)

      - path: nodejs/src/index.ts
        responsibility: Main exports
        exports:
          - Structurify
          - StructurifyError
          - AuthenticationError
          - RateLimitError
          - NotFoundError
          - ValidationError
          - InsufficientCreditsError
          - ServerError
          - verifyWebhookSignature
          - computeSignature
          - Types (StructurifyConfig, Project, Document, etc.)

      - path: nodejs/src/client.ts
        responsibility: Main client class
        features:
          - Native fetch API
          - Automatic retry with exponential backoff
          - Type-safe responses
        methods:
          - get<T>(path, params?)
          - post<T>(path, body?)
          - put<T>(path, body?)
          - delete<T>(path)

      - path: nodejs/src/types.ts
        responsibility: TypeScript type definitions
        types:
          - StructurifyConfig
          - ProjectTemplate, ColumnTemplate
          - Project, Column, Document
          - ExtractionJob, JobStatus
          - Export, ExportFormat, ExportStatus
          - CreateProjectParams, UploadDocumentParams, CreateExportParams
          - WaitOptions

      - path: nodejs/src/errors.ts
        responsibility: Error classes
        classes:
          - StructurifyError
          - AuthenticationError
          - RateLimitError
          - NotFoundError
          - ValidationError
          - InsufficientCreditsError
          - ServerError

      - path: nodejs/src/webhooks.ts
        responsibility: Webhook utilities
        functions:
          - verifyWebhookSignature(params) - HMAC-SHA256 verification
          - computeSignature(payload, secret) - Generate signature

      - path: nodejs/src/resources/templates.ts
        responsibility: Templates resource
        methods:
          - list() - List project templates
          - listColumns() - List column templates
          - get(templateId) - Get specific template

      - path: nodejs/src/resources/projects.ts
        responsibility: Projects resource
        methods:
          - list()
          - get(projectId)
          - create(params: CreateProjectParams)
          - update(projectId, name)
          - delete(projectId)

      - path: nodejs/src/resources/documents.ts
        responsibility: Documents resource
        methods:
          - uploadFromPath(projectId, filePath, name?)
          - upload(params: UploadDocumentParams)
          - get(documentId)
          - getContent(documentId)
          - download(documentId) - Returns Buffer
          - delete(documentId)

      - path: nodejs/src/resources/extraction.ts
        responsibility: Extraction resource
        methods:
          - run(projectId)
          - get(jobId)
          - cancel(jobId)
          - waitForCompletion(jobId, options?: WaitOptions)
          - list(projectId)

      - path: nodejs/src/resources/exports.ts
        responsibility: Exports resource
        methods:
          - create(params: CreateExportParams)
          - get(exportId)
          - download(exportId)
          - list(projectId)
          - delete(exportId)

    usage_example: |
      import { Structurify } from '@structurify/sdk';

      const client = new Structurify({ apiKey: 'sk_live_xxx' });

      // List templates
      const templates = await client.templates.list();

      // Create project from template
      const project = await client.projects.create({
        name: 'Q1 Invoices',
        templateId: 'tpl_invoice'
      });

      // Upload document
      const doc = await client.documents.uploadFromPath(
        project.id,
        './invoice.pdf'
      );

      // Run extraction
      const job = await client.extraction.run(project.id);
      const completed = await client.extraction.waitForCompletion(job.id);

      // Export results
      const result = await client.exports.create({
        projectId: project.id,
        format: 'csv'
      });

  # =============================================================================
  # DOCUMENTATION
  # =============================================================================
  documentation:
    description: API documentation and examples
    files:
      - path: docs/api-reference.md
        responsibility: Complete REST API documentation
        sections:
          - Authentication
          - Rate Limits
          - Templates endpoints
          - Projects endpoints
          - Documents endpoints
          - Extraction Jobs endpoints
          - Exports endpoints
          - Error responses
          - Webhooks

      - path: docs/authentication.md
        responsibility: Authentication guide
        topics:
          - API key format
          - Using API keys
          - Security best practices
          - Environment variables
          - Rate limits
          - Credits

      - path: docs/examples/python/basic_usage.py
        responsibility: Python usage example

      - path: docs/examples/nodejs/basic_usage.ts
        responsibility: Node.js usage example

      - path: docs/examples/curl/basic_usage.sh
        responsibility: cURL usage example

  # =============================================================================
  # WEBHOOKS
  # =============================================================================
  webhooks:
    description: Webhook support for async notifications

    events:
      extraction.completed:
        description: Extraction job finished successfully
        payload:
          event: extraction.completed
          timestamp: ISO 8601
          data:
            job_id: string
            project_id: string
            status: done
            total_tasks: number
            completed_tasks: number
            failed_tasks: number
          signature: "sha256=..."

      extraction.failed:
        description: Extraction job failed completely

      export.ready:
        description: Large export ready for download

    signature_verification:
      algorithm: HMAC-SHA256
      header: X-Structurify-Signature
      format: "sha256=<hex_digest>"

# =============================================================================
# BACKEND REQUIREMENTS (for main Structurify repo)
# =============================================================================
backend_requirements:
  description: |
    These features need to be implemented in the main Structurify repo
    to enable SDK functionality.

  api_keys:
    table: api_keys
    columns:
      - id (TEXT PRIMARY KEY)
      - org_id (TEXT NOT NULL, FK organizations)
      - user_id (TEXT, nullable for org-level keys)
      - name (TEXT NOT NULL)
      - key_hash (TEXT NOT NULL UNIQUE, SHA-256)
      - key_prefix (TEXT NOT NULL, first 8 chars)
      - scopes (TEXT, JSON array)
      - rate_limit_per_minute (INTEGER DEFAULT 60)
      - rate_limit_per_day (INTEGER DEFAULT 10000)
      - last_used_at (TEXT)
      - expires_at (TEXT)
      - created_by (TEXT NOT NULL)
      - created_at (TEXT NOT NULL)
      - revoked_at (TEXT)
      - revoked_by (TEXT)

    endpoints:
      user:
        - POST /api/api-key-requests - Request API access
        - GET /api/api-key-requests - List my requests
      admin:
        - GET /api/admin/api-key-requests - List pending requests
        - POST /api/admin/api-keys - Generate API key
        - GET /api/admin/api-keys/:orgId - List org's keys
        - DELETE /api/admin/api-keys/:id - Revoke key

  api_key_requests:
    table: api_key_requests
    columns:
      - id (TEXT PRIMARY KEY)
      - org_id (TEXT NOT NULL)
      - user_id (TEXT NOT NULL)
      - user_email (TEXT NOT NULL)
      - reason (TEXT)
      - status (TEXT DEFAULT 'pending')
      - reviewed_by (TEXT)
      - reviewed_at (TEXT)
      - created_at (TEXT NOT NULL)

  webhooks:
    table: webhooks
    columns:
      - id (TEXT PRIMARY KEY)
      - org_id (TEXT NOT NULL, FK organizations)
      - url (TEXT NOT NULL)
      - events (TEXT NOT NULL, JSON array)
      - secret (TEXT NOT NULL)
      - is_active (INTEGER DEFAULT 1)
      - last_triggered_at (TEXT)
      - failure_count (INTEGER DEFAULT 0)
      - created_at (TEXT NOT NULL)

# =============================================================================
# PUBLISHING
# =============================================================================
publishing:
  python:
    registry: PyPI
    package: structurify
    command: |
      cd python
      pip install build twine
      python -m build
      twine upload dist/*

  nodejs:
    registry: npm
    package: "@structurify/sdk"
    command: |
      cd nodejs
      npm install
      npm run build
      npm publish --access public

# =============================================================================
# BRANDING
# =============================================================================
branding:
  company: REDSCVRY TECHNOLOGY PRIVATE LIMITED
  website: https://dscvryai.com
  product: Structurify
  product_url: https://structurify.ai
  support_email: support@structurify.ai
  license: MIT
  no_emojis: true
  professional_tone: true
